services:
  app-prod:
    image: todo-front-prod
    build: .

  server-prod:
    image: todo-back-prod
    build: .
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo-prod:27017/the_database?directConnection=true
      - REDIS_URL=redis://redis-prod:6379

  mongo-prod:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis-prod:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data

  nginx-prod:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # ro means read only
    ports:
      - 8080:80
    container_name: todo-app-reverse-proxy
    depends_on:
      - app-prod # wait for the frontend container to be started
      - server-prod
