services:
  app-front-dev:
    image: todo-front-dev
    build: .
    volumes:
      - ./todo-frontend:/usr/src/app
  debug-helper:
    image: busybox

  app-back-dev:
    image: todo-back-dev
    build: .
    volumes:
      - ./todo-backend:/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo-dev:27017/the_database?directConnection=true
      - REDIS_URL=redis://redis-dev:6379

  mongo-dev:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis-dev:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data

  nginx-dev:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro # ro means read only
    ports:
      - 8080:80
    container_name: todo-app-dev-reverse-proxy
    depends_on:
      - app-front-dev # wait for the frontend container to be started
      - app-back-dev
